'use client';

import { useState } from 'react';
import { motion } from 'framer-motion';
import { Zap, Filter, TrendingUp, TrendingDown, Target, Brain } from 'lucide-react';
import { signals } from '@/lib/data';

const filters = ['All', 'BUY', 'SELL', 'Open', 'Closed'];

const strategyColors: Record<string, string> = {
  'Momentum AI': '#00d4ff',
  'Breakout AI': '#8b5cf6',
  'Mean Revert': '#f59e0b',
  'Trend Follow': '#00ff88',
  'Sentiment AI': '#ff4d6d',
};

export default function SignalsPage() {
  const [active, setActive] = useState('All');

  const filtered = signals.filter((s) => {
    if (active === 'All') return true;
    if (active === 'BUY') return s.signal === 'BUY';
    if (active === 'SELL') return s.signal === 'SELL';
    if (active === 'Open') return s.status === 'open';
    if (active === 'Closed') return s.status === 'closed';
    return true;
  });

  return (
    <div className="space-y-6">
      {/* Header */}
      <motion.div
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"
      >
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-[rgba(0,212,255,0.12)] border border-[rgba(0,212,255,0.25)] flex items-center justify-center">
            <Brain size={18} className="text-[#00d4ff]" />
          </div>
          <div>
            <h2 className="text-white font-bold text-lg">AI Trade Signals</h2>
            <p className="text-white/35 text-xs">Generated by Neuro.AI models in real-time</p>
          </div>
        </div>
        <div className="flex items-center gap-2 text-xs text-[#00ff88] font-semibold">
          <span className="dot-live" />
          Live · Updated every 15s
        </div>
      </motion.div>

      {/* Filter tabs */}
      <div className="flex items-center gap-2 flex-wrap">
        <Filter size={14} className="text-white/35" />
        {filters.map((f) => (
          <button
            key={f}
            onClick={() => setActive(f)}
            className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-all ${
              active === f
                ? 'bg-[rgba(0,212,255,0.15)] text-[#00d4ff] border border-[rgba(0,212,255,0.3)]'
                : 'text-white/40 hover:text-white/70 border border-white/8 hover:border-white/15'
            }`}
          >
            {f}
          </button>
        ))}
        <span className="ml-auto text-white/30 text-xs">{filtered.length} signals</span>
      </div>

      {/* Signals grid */}
      <div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-4">
        {filtered.map((s, i) => {
          const stratColor = strategyColors[s.strategy] ?? '#00d4ff';
          const isProfit = s.pnlNum >= 0;
          return (
            <motion.div
              key={s.id}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.06 }}
              className="glass p-5 flex flex-col gap-4 hover:border-white/12 transition-all"
            >
              {/* Top row */}
              <div className="flex items-start justify-between">
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <span className="text-white font-black text-lg">{s.pair}</span>
                    <span className={`badge ${s.signal === 'BUY' ? 'badge-buy' : 'badge-sell'}`}>
                      {s.signal === 'BUY' ? <TrendingUp size={9} className="mr-0.5" /> : <TrendingDown size={9} className="mr-0.5" />}
                      {s.signal}
                    </span>
                  </div>
                  <span
                    className="text-[11px] font-semibold px-2 py-0.5 rounded-md"
                    style={{ background: `${stratColor}15`, color: stratColor }}
                  >
                    {s.strategy}
                  </span>
                </div>
                <span className={`badge ${s.status === 'open' ? 'badge-open' : 'badge-closed'}`}>
                  {s.status}
                </span>
              </div>

              {/* Price levels */}
              <div className="grid grid-cols-3 gap-2 text-center">
                <div className="glass-sm p-2">
                  <p className="text-white/35 text-[10px] mb-0.5">Entry</p>
                  <p className="text-white font-bold text-sm">${s.price.toLocaleString()}</p>
                </div>
                <div className="glass-sm p-2">
                  <p className="text-[#00ff88]/70 text-[10px] mb-0.5">Target</p>
                  <p className="text-[#00ff88] font-bold text-sm">${s.target.toLocaleString()}</p>
                </div>
                <div className="glass-sm p-2">
                  <p className="text-[#ff4d6d]/70 text-[10px] mb-0.5">Stop Loss</p>
                  <p className="text-[#ff4d6d] font-bold text-sm">${s.stopLoss.toLocaleString()}</p>
                </div>
              </div>

              {/* Confidence bar */}
              <div>
                <div className="flex justify-between text-[11px] mb-1.5">
                  <span className="text-white/40 flex items-center gap-1">
                    <Target size={10} /> Confidence
                  </span>
                  <span className="text-white font-semibold">{s.confidence}%</span>
                </div>
                <div className="h-1.5 bg-white/8 rounded-full overflow-hidden">
                  <div
                    className="h-full rounded-full"
                    style={{
                      width: `${s.confidence}%`,
                      background: s.confidence >= 85 ? '#00ff88' : s.confidence >= 75 ? '#00d4ff' : '#f59e0b',
                    }}
                  />
                </div>
              </div>

              {/* Bottom */}
              <div className="flex items-center justify-between pt-1 border-t border-white/5">
                <span className="text-white/35 text-[11px]">{s.time} today</span>
                <span
                  className="font-bold text-sm"
                  style={{ color: isProfit ? '#00ff88' : '#ff4d6d' }}
                >
                  {s.pnl}
                </span>
              </div>
            </motion.div>
          );
        })}
      </div>
    </div>
  );
}
